---
AllCops:
  Exclude:
    - 'Guardfile'
    - 'Rakefile'
    - 'Vagrantfile'
    - 'Policyfile.rb'
    - 'Berksfile'
    - 'Thorfile'
    - 'Gemfile'
    - 'metadata.rb'
    - 'test/**/*'
    - 'vendor/**/*'
    - 'libraries/matchers.rb'

LineLength:
  Enabled: false

ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

MethodLength:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false