---
language: ruby
cache: bundler
sudo: false
script: bundle exec rake travis
before_install:
  - gem update bundler
  - gem update --system
rvm:
  - 2.1
  - 2.2
branches:
  only:
    - master
matrix:
  fast_finish: true